### ISSUE TITLE
Getting issue while starting container 

### ISSUE THREAD

**Issue by anayyar82** [arempter/hive-metastore-docker#5]
docker-compose build
[+] Building 0.9s (7/10)
 => [internal] load build definition from Dockerfile                                                                                                     0.0s
 => => transferring dockerfile: 32B                                                                                                                      0.0s
 => [internal] load .dockerignore                                                                                                                        0.0s
 => => transferring context: 2B                                                                                                                          0.0s
 => [internal] load metadata for docker.io/library/openjdk:8u242-jre                                                                                     0.5s
 => [1/6] FROM docker.io/library/openjdk:8u242-jre@sha256:f437249498cd370546035d6dc73e03a00ec637bcf47b740e60283b2fa7e00fb4                               0.0s
 => [internal] load build context                                                                                                                        0.0s
 => => transferring context: 137B                                                                                                                        0.0s
 => CACHED [2/6] WORKDIR /opt                                                                                                                            0.0s
 => ERROR [3/6] RUN curl -L https://www-us.apache.org/dist/hive/hive-standalone-metastore-3.0.0/hive-standalone-metastore-3.0.0-bin.tar.gz | tar zxf -   0.3s
------
 > [3/6] RUN curl -L https://www-us.apache.org/dist/hive/hive-standalone-metastore-3.0.0/hive-standalone-metastore-3.0.0-bin.tar.gz | tar zxf - &&     curl -L https://archive.apache.org/dist/hadoop/common/hadoop-3.2.0/hadoop-3.2.0.tar.gz | tar zxf - &&     curl -L https://dev.mysql.com/get/Downloads/Connector-J/mysql-connector-java-8.0.19.tar.gz | tar zxf - &&     cp mysql-connector-java-8.0.19/mysql-connector-java-8.0.19.jar /opt/apache-hive-metastore-3.0.0-bin/lib/ &&     rm -rf  mysql-connector-java-8.0.19:
#6 0.296   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
#6 0.298                                  Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (6) Could not resolve host: www-us.apache.org
#6 0.326
#6 0.326 gzip: stdin: unexpected end of file
#6 0.331 /bin/tar: Child returned status 1
#6 0.332 /bin/tar: Error is not recoverable: exiting now
------
failed to solve: rpc error: code = Unknown desc = executor failed running [/bin/sh -c curl -L https://www-us.apache.org/dist/hive/hive-standalone-metastore-${METASTORE_VERSION}/hive-standalone-metastore-${METASTORE_VERSION}-bin.tar.gz | tar zxf - &&     curl -L https://archive.apache.org/dist/hadoop/common/hadoop-${HADOOP_VERSION}/hadoop-${HADOOP_VERSION}.tar.gz | tar zxf - &&     curl -L https://dev.mysql.com/get/Downloads/Connector-J/mysql-connector-java-8.0.19.tar.gz | tar zxf - &&     cp mysql-connector-java-8.0.19/mysql-connector-java-8.0.19.jar ${HIVE_HOME}/lib/ &&     rm -rf  mysql-connector-java-8.0.19]: exit code: 2

**Comment by alexisdondon** [comment]
replace the run command by official download link f apache hive metastore standalone
```
RUN curl -L https://downloads.apache.org/hive/hive-standalone-metastore-${METASTORE_VERSION}/hive-standalone-metastore-${METASTORE_VERSION}-bin.tar.gz | tar zxf - && \
    curl -L https://archive.apache.org/dist/hadoop/common/hadoop-${HADOOP_VERSION}/hadoop-${HADOOP_VERSION}.tar.gz | tar zxf - && \
    curl -L https://dev.mysql.com/get/Downloads/Connector-J/mysql-connector-java-8.0.19.tar.gz | tar zxf - && \
    cp mysql-connector-java-8.0.19/mysql-connector-java-8.0.19.jar ${HIVE_HOME}/lib/ && \
    rm -rf  mysql-connector-java-8.0.19
```
